export const sampleCards = [
    {
      slug: "red",
      name: "Red",
      author: "dog",
      cover: "/",
      published: "厚肉のPMMA成形で特殊技術を保有",
      tags: ["notion", "nextjs"],
      content: "Red page content",
    },
    {
      slug: "green",
      name: "Green",
      author: "cat",
      cover: "/",
      published: "202x-xx-02",
      tags: ["notion"],
      content: "Green page content",
    },
    {
      slug: "blue",
      name: "Blue",
      author: "bird",
      cover: "/",
      published: "202x-xx-03",
      tags: ["react"],
      content: "Blue page content",
    },
    {
      slug: "black",
      name: "Black",
      author: "child",
      cover: "/",
      published: "202x-xx-04",
      tags: ["react","Next"],
      content: "Black page content",
    },
  ];